### ISSUE TITLE
Default config can't be overridden on MacOS

### ISSUE THREAD

**Issue by luckv** [bvieira/sv4git#15]
As the title say the default configuration can't be overridden on MacOS

- **Tool version**: [2.1.1_darwin_amd64](https://github.com/bvieira/sv4git/releases/download/2.1.1/git-sv_2.1.1_darwin_amd64.zip)
- **OS version**: MacOS Catalina 10.15.7
- **Shell**: either `/bin/bash` or `/bin/zsh`
  - `/bin/bash` version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
  - `/bin/zsh` version: zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by bvieira** [comment]
Hi,

Are you using `repo` or `user` config? I tested both using mojave+zsh and seems to be working just fine. 

If it's an user config, did you export `SV4GIT_HOME` variable?

Which config you are trying to overwrite?

**Comment by luckv** [comment]
> Are you using repo or user config?

I tried both


> If it's an user config, did you export `SV4GIT_HOME` variable?

I set it only for the current terminal with `SV4GIT_HOME=/Users/myuser/.sv4git`, but it didn't work

> Which config you are trying to overwrite?

```
version: "1.0" #config version

versioning: # versioning bump
  update-major: [] # commit types used to bump major
  update-minor: # commit types used to bump minor
    - feat
  update-patch: # commit types used to bump patch
    - build
    - ci
    - chore
    - docs
    - fix
    - perf
    - refactor
    - style
    - test
  # when type is not present on update rules and is unknown (not mapped on commit message types),
  # if ignore-unknown=false bump patch, if ignore-unknown=true do not bump version
  ignore-unknown: false

tag:
  pattern: 'v%d.%d.%d' # pattern used to create git tag

release-notes:
  headers: # headers names for relase notes markdown, to disable a section, just remove the header line
    breaking-change: Breaking Changes
    feat: Features
    fix: Bug Fixes

branches: # git branches config
  prefix: ([a-z]+\/)? # prefix used on branch name, should be a regex group
  suffix: (-.*)? # suffix used on branch name, should be a regex group
  disable-issue: false # set true if there is no need to recover issue id from branch name
  skip: # list of branch names ignored on commit message validation
      - master
      - dev
  skip-detached: false # set true if a detached branch should be ignored on commit message validation

commit-message:
  types: # supported commit types
    - build
    - ci
    - chore
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  scope:
    # define supported scopes, if blank, scope will not be validated, if not, only scope listed will be valid.
    # don't forget to add "" on your list if you need to define scopes and keep it optional
    values: []
  footer:
    issue: # use "issue: {}" if you wish to disable issue footer
      key: jira # name used to define an issue on footer metadata
      key-synonyms: # supported variations for footer metadata
        - Jira
        - JIRA
      use-hash: false # if false, use :<space> separator, if true, use <space># separator
  issue:
    regex: '[A-Z]+-[0-9]+' # regex for issue id
```

**Comment by bvieira** [comment]
> > If it's an user config, did you export `SV4GIT_HOME` variable?
> 
> I set it only for the current terminal with `SV4GIT_HOME=/Users/myuser/.sv4git`, but it didn't work

if you run `ls -l $SV4GIT_HOME/config.yml`, the file exists?

I added a debug flag to sv4git, could you please run `git-sv --debug cfg show` using [git-sv_dev-202104082345_darwin_amd64.zip](https://github.com/bvieira/sv4git/files/6282833/git-sv_dev-202104082345_darwin_amd64.zip) and send me the output? It will show a warning if it fails to load repo or user configs.

You are trying to overwrite `tag.pattern` and `branches.skip`, right?
there is no need to write every config, you can add only what you need to change, eg:

```yaml
version: "1.0"
tag:
    pattern: 'v%d.%d.%d'
branches:
    skip:
        - master
        - dev
```

**Comment by luckv** [comment]
> if you run `ls -l $SV4GIT_HOME/config.yml`, the file exists?

No, but if I run `echo $SV4GIT_HOME` it prints correctly `/Users/myuser/.sv4git`

> could you please run `git-sv --debug cfg show`

I run the executable you passed but no warning showed up.
```
version: "1.0"
versioning:
    update-major: []
    update-minor:
        - feat
    update-patch:
        - build
        - ci
        - chore
        - docs
        - fix
        - perf
        - refactor
        - style
        - test
    ignore-unknown: false
tag:
    pattern: v%d.%d.%d
release-notes:
    headers:
        breaking-change: Breaking Changes
        feat: Features
        fix: Bug Fixes
branches:
    prefix: ([a-z]+\/)?
    suffix: (-.*)?
    disable-issue: false
    skip:
        - master
        - main
        - developer
    skip-detached: false
commit-message:
    types:
        - build
        - ci
        - chore
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
    scope:
        values: []
    footer:
        issue:
            key: jira
            key-synonyms:
                - Jira
                - JIRA
            use-hash: false
    issue:
        regex: '[A-Z]+-[0-9]+'


```
